config/routes.rb
RailsApp3::Application.routes.draw do
  get "chat/send"

  get "chat/send_message"

  get "relationships/create"

  get "relationships/destroy"

  resources :users do
		member do 
			get :friends
		end 
	end 

  resources :sessions,   :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy, :update]
  
  match 'signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/help',    :to => 'microposts#help'

	match 'picture_upload', :to => 'users#picture'
  match '/search', :to => 'users#index'

	match '/chat/send', :controller => 'chat', :action => 'send'

  root :to => 'users#home'

end

app/models/user.rb
require 'digest'

class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :photo

  cattr_reader :per_page
  @@per_page = 10

  validates_attachment_size :photo, :less_than => 100.kilobytes

  has_attached_file :photo,
                    :styles => {:thumb => "50x50>"},
                    :storage => :s3,
                    :s3_credentials => S3_CREDENTIALS,
                    :whiny_thumbnails => true

	has_many :user_images, :dependent => :destroy

	has_many  :microposts, :dependent => :destroy
  
  has_many  :relationships, :foreign_key => "user_id", :dependent => :destroy
  has_many  :friends, :through => :relationships,
                      :foreign_key => "friend_id",
                      :class_name => "User",
                      :conditions => ['relationships.approved = ?', true]

	has_many  :reverse_relationships, :foreign_key => "friend_id",
                                    :class_name  => "Relationship",
                                    :dependent   => :destroy

 has_many   :users,  :through => :reverse_relationships,
                        :foreign_key => "user_id",
                        :class_name => "User"

  #TODO: put limitations on email format with regexp
  #TODO: change :password length between 6..20
  validates :name, :presence => true, :length => { :maximum => 50 }
  validates :email, :presence => true, :uniqueness => { :case_sensitive => false }
  validates :password, :presence => true, :confirmation => true, :length => { :within => 1..20 }
  
  before_save :encrypt_password

	def feed
  	Micropost.from_users_followed_by(self)
	end 

  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    ( user && user.salt == cookie_salt ) ? user : nil
  end

  def friend?(user)
    #return false if not a friend or not approved.
    friend = relationships.find_by_friend_id(user)
    friend.nil? ? false : friend.approved?
  end

  #return a list of pending friendships
  def pending_friends
    Relationship.find_all_by_friend_id_and_approved(self,false)
  end

  def addAsFriend!(user)
    relationships.create(:friend_id => user.id)
  end

  def waitingForApproval?(user)
    rel = Relationship.find_by_user_id_and_friend_id(user, self)
    rel.nil? ? false : !rel.approved?
  end

  def self.search(term)
    if term
      results = User.where("name  = ?", term)
    else
      results = User.all
    end
    return results
  end


  private
  
  def encrypt_password
    self.salt = make_salt if new_record?
    self.encrypted_password = encrypt(password)
  end

  def encrypt(string)
    secure_hash("#{salt}--#{string}")
  end

  def make_salt
    secure_hash("#{Time.now.utc}--#{password}")
  end

  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end
  
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_filter :authenticate, :only => [:edit, :update, :index, :show]
	before_filter :correct_user, :only => [:edit, :update]
	before_filter :admin_user,   :only => :destroy

	

	def index
		
		@title = "Search"
		@user  = current_user
    #@users =  User.search(params[:search])
    return if params[:search] == nil
    
    regexp = /.*#{params[:search]}.*/i
    @userNames = Array.new
    User.select(:name).select(:id).each do |name|
      if( name.name =~ regexp )
        @userNames.push(name.id)
      end    
    end
    @users = User.find(@userNames)

		end


	def home
		if signed_in?
			@user = current_user
			redirect_to current_user			
		else 
			#display home
		end 
	end 
 
  def new
    @user = User.new
    @title = "Welcome new user!"
  end

	def friends 
		@user = current_user
	end 
  
  def show
		 
		@user = User.find(params[:id])		
		@title = @user.name
		@micropost = Micropost.new if signed_in?
		
		@microposts = Micropost.find_all_by_recipient(@user).paginate(:page => params[:page])
		

		@count = @user.user_images.count
		if @count >= 1
			@AllImages = @user.user_images.all
			@rand = rand(@AllImages.count) % @AllImages.count
			@image = @AllImages[@rand]
		else 			
			@image = nil
 		end 
  end

  def create
    @user = User.new(params[:user])
    if @user.save 
      sign_in @user
      flash[:success] = "Welcome to Uconn's own social network!"
      redirect_to @user
    else
      @title = "Sign up: Error"
      render 'new'
    end
  end

	def destroy
		user = User.find(params[:id])
		flash[:success] = "Deleted #{user.name}."
		user.destroy
		redirect_to users_path
	end 

	def edit 
 		@title = "Edit"
	end 

	def update
    debugger
    @user = User.find(params[:id])
		if @user.update_attributes(params[:user])
			flash[:success] = "Updated successfully"
			redirect_to @user
		else 
			@title = "Edit"
			render 'edit'
		end 
	end

def following 
	@title = "Following"
	@user = User.find(params[:id])
	@users = @user.following.paginate(:page => params[:page])
	render 'show_follow'
end  

def followers
	@title = "Followers"
	@user  = User.find(params[:id])
        @users = @user.followers.paginate(:page => params[:page])
	render 'show_follow'
end


def picture

	@user = current_user
	@image =	@user.user_images.build(:photo => params[:user_images][:photo])
	
	if @image.save 
		flash[:success] = "Picture uploaded"			
	else 
		flash[:error] = "Picture could not be uploaded"			
	end 
end



	private 

	def admin_user
		redirect_to root_path unless current_user.admin?
	end 
	
	def correct_user
		@user = User.find(params[:id])
		redirect_to(root_path) unless current_user?(@user)
	end 


end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
		       :class => 'gravatar', 
		       :gravatar => options)
  end

end

app/views/users/_chat_form.html.erb
<div id="incoming_msg"></div>

<script type="text/javascript" charset="utf-8">
  var jug = new Juggernaut();

  jug.subscribe("/chat/<%= current_user.id %>", function(data){
  var li = $("<li/>");
  li.text(data);
  $("#incoming_msg").append(li);
});

var jug2 = new Juggernaut();

  jug2.subscribe("/chat/global", function(data){
  var li = $("<li/>");
  li.text(data);
  $("#incoming_msg").append(li);

  var disp = $("#incoming_msg").scrollTop();
  $("#incoming_msg").scrollTop(disp + 30);
});

</script>


<% form_tag('/chat/send', :id => 'chat_window', :remote => true) do %>

<%= text_field_tag 'msg_body', '', :size => 15 %>
<%= hidden_field_tag 'sender', current_user.name %>
<%= submit_tag 'Send Message' %>

<% end %>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:friend_id => @user.id)  do |f|  %>
 
 <div> <%= f.hidden_field :friend_id %></div>
 <div class="actions"><%= f.submit "Add as Friend" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
 <div id="follow_form">
   <% if @user.friend?(current_user) %>
    <%= render 'unfollow' %>
   <% elsif @user.waitingForApproval?(current_user) || current_user.waitingForApproval?(@user) %>
    waiting for approval
   <% else  %>
       <%= render 'follow'   %>
   <% end %>
 </div> 
<% end %>

app/views/users/edit.html.erb
<h1> Edit User</h1>

<%= form_for(@user, :html => { :multipart => true}) do |f| %>
<%= render 'shared/error_messages', :object => f.object %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>    
</div>

<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>

<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>

<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %>
</div>

<div class="field">
  <%= f.label :photo, "Profile Picture" %><br />
  <%= f.file_field :photo  %>
</div>

<div class="actons">
  <%= f.submit "Update" %>
</div>

<% end %>

<br />

<h2>Upload picture<h2>
<%= form_for(:user_images, :url => picture_upload_path , :html=>{:multipart=>true}) do |f|  %>

<div class="field">
  <%= f.file_field :photo %>
</div>

<div class="actions">
  <%= f.submit "Upload" %>
</div>

<% end %>

app/views/users/friends.html.erb
<% User.find(params[:id]).friends.each do |fri| %>
   <%= link_to fri.name, fri%><br />

<% end %>

app/views/users/home.html.erb
<h2> Uconn::Social </h2>
<p> Welcome to the gathering place for college students </p>

<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/index.html.erb
<%= form_tag search_path, :method => 'get' do %>
    <%= content_tag :label do %>
        Search:
        <%= text_field_tag :search, params[:search] %>
        <% end %>        
<% end %>

<% unless @users.nil?  %>
    <% @users.each do |user| %>
      <%= link_to user.name, user %><br/>
    <% end %>
<% end %>

app/views/users/index.js.erb
$("section#main_content").empty().append('<%= form_tag search_path, :method => 'get', :remote => true do %><%= content_tag :label do %>Search:<%= text_field_tag :search, params[:search] %><% end %><% end %>' +
                                              '<% unless @users.nil?  %>' +
                                              '<% @users.each do |user| %>' +
                                              '<%= link_to user.name, user %><br/>' +
                                              '<% end %>' +
                                              '<% end %>' +
                                              '<br></br>');

app/views/users/new.html.erb
<h3>Please fill out the following form:</h3>

<%= form_for(@user) do |f| %>
<%= render 'shared/error_messages' %>
<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
    <%= f.label :password_confirmation, "Re-enter password" %><br />
    <%= f.password_field :password_confirmation %>
</div>

<div class="actions">
  <%= f.submit "Sign up" %>
</div>

<% end %>

app/views/users/picture.html.erb
<h1>Picture uploaded </h1>

app/views/users/show.html.erb
<table class="profile" summary="User Information">
  <tr>
    <td class="main">
        <% if current_user?(@user) || current_user.friend?(@user) %>
	      <%= render 'shared/micropost_form' %>
        <% else %>
            <p> add <%= @user.name %> as a friend to post</p>
        <% end %>           
    </td>
    <td class="sidebar round">
      <strong><%= image_tag @user.photo.url(:thumb) %> <br /> <%= @user.name %> </strong><br /><br />
      <strong>URL:</strong>  <%= link_to user_path(@user), @user %> <br />
      <strong>Posts:</strong> <span id="user_post_count"><%= @user.microposts.count %></span>
    </td>
  </tr>
</table>

<% unless @microposts.nil?  %>
<table id="user_feed" class="microposts" summary="User posts">
  <%= render @microposts %>
</table> 
<%= will_paginate @microposts %>
<% end %> 

<% content_for :friends_tab do  render 'shared/stats'  end %>


<% content_for :friends_tab do  render 'follow_form'   end %>

<% content_for :picture_of_the_day do %>
<% if !@image.nil? %>
 <%=  image_tag @image.photo.url(:thumb)  %>
<% end %> 
<% end %>

<% #debugger
   if current_user?(@user)
    pending_users = @user.pending_friends   
    unless pending_users.nil?
      #debugger
      content_for :messages_tab do render pending_users end
    end 
   end     
%>

app/views/users/show_follow.html.erb
<% unless @users.empty? %>
<table summary="Showing following/follwer user(s)">
 <% @users.each do |user| %>
<tr>
  <td>
    <%= link_to user.name, user %>
  </td>
</tr>
<% end %>
</table>
<%= will_paginate @users %>
<% end %>