config/routes.rb
RailsApp3::Application.routes.draw do
  get "chat/send"

  get "chat/send_message"

  get "relationships/create"

  get "relationships/destroy"

  resources :users do
		member do 
			get :friends
		end 
	end 

  resources :sessions,   :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy, :update]
  
  match 'signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/help',    :to => 'microposts#help'

	match 'picture_upload', :to => 'users#picture'
  match '/search', :to => 'users#index'

	match '/chat/send', :controller => 'chat', :action => 'send'

  root :to => 'users#home'

end

app/views/shared/_error_messages.html.erb
<%if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, "error") %> was found in
   <%= object.class.to_s.underscore.humanize.downcase %></h2>
  <p>Please correct the following fields:</p>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li> <%= msg %> </li>
    <% end %>
  </ul>
</div>

<% end %>
    

app/views/shared/_feed.html.erb
<% unless @feed_items.empty? %>
<%= render :partial => 'shared/feed_items', :collection => @feed_items %>
<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_items.html.erb
<tr> 
  <td class ="micropost">
  <span class="user"> 
    
    <% link_to feed_items.user.name, feed_items.user %>
  </span>
  <span class="content"> <%= feed_items.content %></span>
  <span class="timestamp"> 
    Posted <%= time_ago_in_words(feed_items.created_at) %> ago.
  </span>
  </td>

  <% if current_user?(feed_items.user) %>
  <td> <%= link_to "delete", feed_items, :method => :delete,
                                       :confirm => "Delete post?",
                                       :title => feed_items.content %>
  </td>  
  <% end %>
  
</tr>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, :remote => true do |f| %> 
 <%= render 'shared/error_messages', :object => f.object %>
 <div class="field">
   <%= f.text_area :content %>
 </div> 
<div class="field">
 <%= f.hidden_field :recipient, :value => @user.id  %>
</div>
 <div class="actions">
   <%= f.submit "Post!" %>
 </div> 
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<div class="stats">
  <table summary="User status">
    <tr> 
      <td> 
        <a href="<%= friends_user_path(@user) %>">
          <span id="following" class="stat">
            <%= count = @user.friends.count
                pluralize(count, 'friend')%>
          </span>
        </a>
      </td>

    </tr>
  </table>
</div>