config/routes.rb
RailsApp3::Application.routes.draw do
  get "chat/send"

  get "chat/send_message"

  get "relationships/create"

  get "relationships/destroy"

  resources :users do
		member do 
			get :friends
		end 
	end 

  resources :sessions,   :only => [:new, :create, :destroy]
	resources :microposts, :only => [:create, :destroy]
	resources :relationships, :only => [:create, :destroy, :update]
  
  match 'signup',   :to => 'users#new'
  match '/signin',   :to => 'sessions#new'
  match '/signout',  :to => 'sessions#destroy'
  match '/help',    :to => 'microposts#help'

	match 'picture_upload', :to => 'users#picture'
  match '/search', :to => 'users#index'

	match '/chat/send', :controller => 'chat', :action => 'send'

  root :to => 'users#home'

end

app/views/layouts/_header.html.erb
<div id="header" class="span-11"> <%= image_tag("Uconn-Social-Logo.png") %> </div>
<nav class="span-7 last round prepend-top">
  <ul>
    <% if signed_in? %>
    <li><%= link_to "Search", search_path, :remote => true %> </li>
	  <li><%= link_to "Wall", root_path %></li>
	  <li><%= link_to "Settings", edit_user_path(current_user) %></li>
    <li><%= link_to "Sign out", signout_path %></li>
   	<% else %>
    <li><%= link_to "Home", root_path %> </li>
	  <li><%= link_to "Sign In", signin_path %> </li>
	  <% end %> 
  </ul>
</nav>

app/views/layouts/_stylesheets.html.erb
  <%= stylesheet_link_tag :all %>
  <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen'  %>
  <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
  <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%=  title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <script src="http://d1535.dyndns-server.com:8080/application.js" type="text/javascript" charset="utf-8"></script>
  <script type="text/javascript" src="/javascripts/jquery.dimensions.min.js"></script>

<script language="javascript">

  var name = "#chat_tab";
  var menuYloc = null;


  $(document).ready(function(){

  //menuYloc = parseInt( $(name).css("top").substring(0, $(name).css("top").indexOf("px") ) )

  var disp = $(window).height() -150;
  $("#chat_tab").css("top", disp + 'px');

  $(window).scroll(function() {
  var offset = disp + $(document).scrollTop() + "px";
  $(name).animate({top:offset}, {duration:200,queue:false});

  });

  });

</script>
</head>
<body>
  <div class="container" >

    <div class="span-20 prepend-top " > </div>

    <%= render 'layouts/header' %>

     <% if content_for?(:messages_tab) %>
           <section class="span-17  round"> <%= yield :messages_tab %></section>
     <% end  %>


    <section id="main_content" class="span-17 round">
      <% flash.each do |key, value| %>
      <div class="flash <%= key %>"> <%= value %> </div>
      <% end %>
      <%= yield %> 
    </section>

    <% if content_for?(:debug) %>
      <section class="span-5 last"> Test: <%= yield :debug %> </section>      
    <% end %>

    <% if content_for?(:friends_tab) %>
      <section id="friends_tab" class="span-5 last round"><%= yield :friends_tab %> </section>
    <% end %>

    <% if content_for?(:picture_of_the_day) %>
     <section class="span-5 last round">
       <p > Picture of the Day </p>
       <%= yield :picture_of_the_day %>
     </section>
    <% end %> 


<% 
=begin %> 
<% if content_for?(:chat_tab) %>
<section id="chat_tab" class="span-5 round"> <%= yield :chat_tab %> </section>
<div class="http://d1535.dyndns-server.com:8080"></div>
<% end %> 
<% 
=end %>

<% if signed_in? %>

 <section id="chat_tab" class="span-15 round"><%= render 'chat_form' %></section>


      <div class="span-19 prepend-top last"> 
        <% image_tag("footer.png") %>
      </div>
<% end %>


  </div>

</body>
</html>